FROM stereolabs/zed:4.1-tools-devel-l4t-r36.3

# install ROS humble
RUN apt-get update
RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
RUN locale

RUN apt install software-properties-common -y
RUN add-apt-repository universe

RUN apt-get install curl -y
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt-get update
RUN apt-get install ros-humble-desktop -y
RUN apt-get install ros-dev-tools -y

RUN rosdep init
RUN rosdep update

RUN /bin/bash -c "echo source /opt/ros/humble/setup.bash >> ~/.bashrc"

# setup ros2 zed wrapper repository (runtime build)
WORKDIR /root
RUN mkdir -p ~/ros2_ws/src/
# Move to the `src` folder of the ROS 2 Workspace
WORKDIR /root/ros2_ws/src/
RUN git clone --recurse-submodules https://github.com/stereolabs/zed-ros2-wrapper.git
WORKDIR /root/ros2_ws/

RUN /bin/bash -c "source /opt/ros/humble/setup.bash && \
  apt-get update && \
  rosdep install --from-paths src --ignore-src -r -y && \
  colcon build --parallel-workers $(nproc) --symlink-install \
  --event-handlers console_direct+ --base-paths src \
  --cmake-args ' -DCMAKE_BUILD_TYPE=Release' \
  ' -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs' \
  ' -DCMAKE_CXX_FLAGS="-Wl,--allow-shlib-undefined"' \
  ' --no-warn-unused-cli' "

RUN /bin/bash -c "echo source /root/ros2_ws/install/setup.bash >> ~/.bashrc"
